In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv(r"D:\Downloads\data of gurugram real Estate.csv.zip")
df.head()

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
0,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
1,14400000.0,Under Construction,1528,"9,450",3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment
2,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
3,40000000.0,Ready to move,4500,"8,888",4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,4.0,Outside Socity,Outside,Plot
4,24000000.0,Under Construction,1800,"13,333",3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19515 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          19515 non-null  object
 1   Status         19515 non-null  object
 2   Area           19515 non-null  int64
 3   Rate per sqft  19515 non-null  object
 4   Property Type  19515 non-null  object
 5   Locality       19515 non-null  object
 6   Builder Name   19515 non-null  object
 7   RERA Approval  19515 non-null  object
 8   BHK_Count      19515 non-null  float64
 9   Socity         19515 non-null  object
 10  Company Name   19515 non-null  object
 11  Flat Type      19515 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 1.8+ MB

In [14]:
df.shape

(19515, 12)

In [16]:
df.columns

Index(['Price', 'Status', 'Area', 'Rate per sqft', 'Property Type', 'Locality',
       'Builder Name', 'RERA Approval', 'BHK_Count', 'Socity', 'Company Name',
       'Flat Type'],
      dtype='object')

In [18]:
df.describe()

                Area     BHK_Count
count   19515.000000  19515.000000
mean     2545.455752      3.229772
std      9550.629288      4.923873
min        60.000000      0.000000
25%      1423.000000      3.000000
50%      2000.000000      3.000000
75%      2800.000000      4.000000
max    958320.000000    132.000000

In [23]:
# CHECK MISSING VALUES
df.isnull().sum()

Price            0
Status           0
Area             0
Rate per sqft    0
Property Type    0
Locality         0
Builder Name     0
RERA Approval    0
BHK_Count        0
Socity           0
Company Name     0
Flat Type        0
dtype: int64

In [25]:
# CHECK DUPLICATE VALUES
df.duplicated().sum()

5292

In [27]:
df[['Price', 'Rate per sqft']].head(10)

        Price Rate per sqft
0  10700000.0        9,450
1  14400000.0        9,450
2  10700000.0        9,450
3  40000000.0        8,888
4  24000000.0       13,333
5  63800000.0       28,000
6   4500000.0        4,891
7   4500000.0        4,500
8   9000000.0        7,200
9  74900000.0       19,736

In [29]:
df[['Price', 'Rate per sqft']].dtypes

Price            object
Rate per sqft    object
dtype: object

In [31]:
# Duplicate rows inspect
df[df.duplicated()].head(10)

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
144,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
145,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
146,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
147,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
148,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
149,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
150,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
151,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
152,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot
153,4500000.0,Ready to move,920,"4,891",3 BHK Apartment,Sector 3A,seller,Not approved by RERA,3.0,Outside Socity,Outside,Plot

In [37]:
# CHECK Actual Python data types
type(df['Price'].iloc[0]), type(df['Rate per sqft'].iloc[0])

(str, str)

In [1]:
cd /d D:\DataAnalytics

[WinError 123] The filename, directory name, or volume label syntax is incorrect: '/d D:\\DataAnalytics'
C:\Users\hp